<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>PCBInspection.UI</AssemblyName>
    <RootNamespace>PCBInspection.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.7.0.20230124" />
  </ItemGroup>
</Project>